### ISSUE TITLE
Diagram name border not extending when diagram attributes is too big

### ISSUE THREAD

**Issue by lizardoluis** [lizardoluis/omtg-designer#4]
![screen shot 2016-07-12 at 1 32 09 pm](https://cloud.githubusercontent.com/assets/2699897/16775071/5160c47e-4835-11e6-99f3-71f0379b8914.png)

Header on conventional class is also wrong due to -1 on margin.

![screen shot 2016-07-12 at 3 18 38 pm](https://cloud.githubusercontent.com/assets/2699897/16778366/1d26f566-4844-11e6-8b93-80ebc3a5c516.png)

**Comment by arthurcamara1** [comment]
Instead of `margin-left: -1px` for `.d-title`, add this:

```css
.d-icon ~ .d-title {
    margin-left: -1px;
}
```

This will ensure only elements `.d-title` that are _siblings_ of `.d-icon` will get the margin style.

**Comment by arthurcamara1** [comment]
Alright, change of plans. This should do the trick:

```css
.diagram-container .d-header .d-icon ~ .d-title {
    padding-left: 45px;
}
//remove margin-left: -1

.diagram-container .d-header .d-title {
    height: 100%;
    min-width: 100px;
    border: 1px solid black;
    font-weight: bold;
    padding: 8px 10px 5px 10px;
    white-space: nowrap;
}
//remove display: inline-block, text-align: center and margin-left
```
